# Generated by Django 5.2.16 on 2026-07-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_add_contact_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='whatsapp_access_token',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='business',
            name='whatsapp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='whatsapp_phone_number_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='business',
            name='whatsapp_verify_token',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
