from django.urls import path

from .views import (
    AppointmentCancelView,
    AppointmentConfirmView,
    AppointmentCreateView,
    AppointmentDetailView,
    AppointmentsListView,
    AppointmentUpdateView,
    CustomerCreateView,
    CustomersListView,
    DashboardView,
    LoginView,
    LogoutView,
    ServiceCreateView,
    ServicesListView,
    StaffCreateView,
    StaffListView,
    UpcomingAppointmentsView,
)

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("dashboard/", DashboardView.as_view(), name="dashboard"),
    path(
        "appointments/upcoming/",
        UpcomingAppointmentsView.as_view(),
        name="upcoming_appointments",
    ),
    path(
        "appointments/",
        AppointmentsListView.as_view(),
        name="appointments_list",
    ),
    path(
        "appointments/create/",
        AppointmentCreateView.as_view(),
        name="appointments_create",
    ),
    path(
        "appointments/<uuid:appointment_id>/cancel/",
        AppointmentCancelView.as_view(),
        name="appointments_cancel",
    ),
    path(
        "appointments/<uuid:appointment_id>/confirm/",
        AppointmentConfirmView.as_view(),
        name="appointments_confirm",
    ),
    path(
        "appointments/<uuid:appointment_id>/",
        AppointmentDetailView.as_view(),
        name="appointments_detail",
    ),
    path(
        "appointments/<uuid:appointment_id>/edit/",
        AppointmentUpdateView.as_view(),
        name="appointments_edit",
    ),
    path(
        "customers/",
        CustomersListView.as_view(),
        name="customers_list",
    ),
    path(
        "customers/create/",
        CustomerCreateView.as_view(),
        name="customers_create",
    ),
    path(
        "services/",
        ServicesListView.as_view(),
        name="services_list",
    ),
    path(
        "services/create/",
        ServiceCreateView.as_view(),
        name="services_create",
    ),
    path(
        "staff/",
        StaffListView.as_view(),
        name="staff_list",
    ),
    path(
        "staff/create/",
        StaffCreateView.as_view(),
        name="staff_create",
    ),
]
