# Generated by Django 5.2.16 on 2026-07-16 15:04

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppBusinessAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number_id', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('verified_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_account', to='businesses.business')),
            ],
            options={
                'db_table': 'whatsapp_business_accounts',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_events', to='businesses.business')),
            ],
            options={
                'db_table': 'whatsapp_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'created_at'], name='whatsapp_ev_busines_cdb693_idx'), models.Index(fields=['event_id'], name='whatsapp_ev_event_i_04443c_idx')],
            },
        ),
    ]
