# Generated by Django 5.2.16 on 2026-07-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='context_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
